#! /usr/bin/env bash

# Shows the output of every command
set +x

activate_hm() {
  HOME_MANAGER_BACKUP_EXT=bak result/activate
  hm-changes-report
}

rebuild_hyprland_edp() {
  nix build .#homeConfigurations.hyprland-edp.activationPackage
  activate_hm
}

rebuild_hyprland_hdmi() {
  nix build .#homeConfigurations.hyprland-hdmi.activationPackage
  activate_hm
}

rebuild_lenovo() {
  # nix build .#nixosConfigurations.lenovo-yoga.config.system.build.toplevel
  # sudo result/bin/switch-to-configuration switch
  sudo nixos-rebuild switch --flake .#lenovo-yoga
}

rebuild_meshify() {
  # nix build .#nixosConfigurations.lenovo-yoga.config.system.build.toplevel
  # sudo result/bin/switch-to-configuration switch
  sudo nixos-rebuild switch --flake .#meshify-pc
}

rebuild_lenovo_vm() {
  nixos-rebuild build-vm --flake .#lenovo-yoga
}

case $1 in
  "hpedp")
    rebuild_hyprland_edp;;
  "hphdmi")
    rebuild_hyprland_hdmi;;
  "lenovo")
    rebuild_lenovo;;
  "meshify")
    rebuild_meshify;;
  "vm")
    rebuild_lenovo_vm;;
  *)
    echo "Wrong argument: look at the switch script.";;
esac
